name: CI (lint + import)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black

      - name: Format check (black)
        run: black --check src/ examples/

      - name: Smoke import
        run: |
          python - << 'PY'
          import importlib
          for m in [
              "utils",
              "multi_sensor_dataset",
          ]:
              importlib.import_module(m)
              print(f"OK import: {m}")
          PY
