name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch  # or add in requirements.txt
          pip install black 


      - name: Format check with black
        run: |
          black --check src/
      # - name: Run basic dataset pipeline
      #   run: |
      #     mkdir -p out
      #     python src/00_inspect_mcap.py --mcap kitti.mcap --save-sample
      #     python src/01_split_chunks.py
      #     python src/02_build_dataset.py

      # - name: Validate dataset
      #   run: |
      #     python src/03_validate_dataset.py --root out/dataset --samples-per-scene 1

